---
parser: babel-eslint

env:
  node: true
  jest: true

plugins:
  - jest
  - babel
  - lodash
  - import

extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:lodash/recommended
  - plugin:import/errors
  - plugin:import/warnings

rules:
  no-console: off
  lodash/import-scope:
    - 2
    - full
  lodash/chaining:
    - 2
    - always
    - 3
